name: Manjaro Mirror Fasttrack Container

on:
  schedule:
    - cron:  '30 5 * * *'

  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'With TMATE'
        required: false
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      # image: archlinux:latest
      image: manjarolinux/base:latest
      # volumes:
      #   - /imagegeneration:/lixo/imagegeneration
      #   - /opt:/lixo/opt
      #   - /usr:/lixo/usr

    steps:
      - uses: actions/checkout@v3
      
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      
      # - name: Clean System
      #   shell: bash -O extglob {0}
      #   run: |
      #     echo "Clean System"
      #     df -h
      #     rm -rf /__t
      #     rm -rf \
      #     /lixo/imagegeneration \
      #     /lixo/opt/az \
      #     /lixo/opt/ghc \
      #     /lixo/opt/pipx \
      #     /lixo/opt/google \
      #     /lixo/opt/microsoft \
      #     /lixo/opt/hostedtoolcache \
      #     /lixo/usr/lib/gcc \
      #     /lixo/usr/lib/llvm* \
      #     /lixo/var/lib/mysql \
      #     /lixo/var/lib/snapd \
      #     /lixo/var/lib/docker \
      #     /lixo/usr/lib/google* \
      #     /lixo/usr/lib/firefox \
      #     /lixo/usr/local/julia* \
      #     /lixo/usr/local/.ghcup \
      #     /lixo/usr/local/aws-cli \
      #     /lixo/usr/local/lib/android \
      #     /lixo/usr/local/aws-sam-cli \
      #     /lixo/usr/local/share/chromium \
      #     /lixo/usr/local/lib/node_modules \
      #     /lixo/usr/local/share/powershell \
      #     /lixo/usr/share/swift \
      #     /lixo/usr/share/dotnet
      #     echo "End Clean System"
      #     df -h
        
      - name: Install Dependencies
        shell: bash
        run: |
          # echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          pacman -Syu --noconfirm --needed tmate pacman-mirrors git openssh
          
      - name: SSH Setup
        shell: bash
        run: |
          mkdir -p ~/.ssh
          > ~/.ssh/github_actions
          chmod 600 ~/.ssh/github_actions
          echo "${{ secrets.PACKAGE_BUILD_KEY }}" >> ~/.ssh/github_actions
          eval `ssh-agent -s`
          ssh-add ~/.ssh/github_actions
          ssh-keyscan -t ed25519 github.com > /root/.ssh/known_hosts
          
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
          install-dependencies: false
          
      - name: Mirrors Fasttrack
        shell: bash
        run: |
          git clone git@github.com:BigLinux-Package-Build/manjaro-mirror.git
          cd manjaro-mirror
          sudo pacman-mirrors --geoip
          cp /etc/pacman.d/mirrorlist $PWD
          sed -i '/#/d;/^$/d' mirrorlist
          
      - name: Update github
        run: |
          cd manjaro-mirror
          git add --all
          git config --local user.email "${{ secrets.GIT_USER }}@users.noreply.github.com"
          git config --local user.name "${{ secrets.GIT_USER }}"
          if [ -n "$(git commit -m "update $(date +%Y-%m-%d)" -a | grep "nothing to commit")" ];then exit 0; fi
          git push
          
